# Site wide configuration

title: Anonymousy
locale: zh_CN
description: FA♂Q
logo: site-logo.png
search: true
url: http://blog.hhhhhhhhhhhush.xyz

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "memorandum.md", "vendor"]


# Site owner
owner:
  name: Hush Please
  avatar: bio-photo-3.jpg
  email: hush@xianyu.io
  disqus-shortname: hush
  twitter: Hush_Please_
  facebook: #username
  github: hushPlease
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: HUSH.PLEASE
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: Hush丶Please
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
